# Docker compose files used for testing in container
version: '3'

services:
  supabase-discord-auth:
    image: supabase-discord-auth
    container_name: supabase-discord-auth
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: unless-stopped
    environment:
      NODE_ENV: ${NODE_ENV}
      PORT: ${PORT}
      CLIENT_APP_URL: ${CLIENT_APP_URL}
      APP_HOST_NAME: ${APP_HOST_NAME}
      SUPABASE_ANON_KEY: ${SUPABASE_ANON_KEY}
      SUPABASE_SERVICE_URL: ${SUPABASE_SERVICE_URL}
    ports:
      - "${PORT}:${PORT}"
    networks:
      - auth

networks:
  auth: